 name: Jetpack
 version: 1.1.4
 description: Jetpack !
 author: SeaMoon15
 main: fr.seamoon.jetpack.JetpackMain
 depend: [ProtocolLib]
 api-version: 1.13
 commands:
   jetpack:
      description: Spawn a jetpack !